//              Copyright (C) by UCAR
//
// File       : $RCSfile: nc_close.cxx,v $
// Revision   : $Revision$
// Directory  : $Source: /code/cvs/pam/isff/src/nc_server/nc_close.cxx,v $
// System     : PAM
// Date       : $Date$
//
// Description:
//
// Updates    : $Log: nc_close.cxx,v $
// Updates    : Revision 1.4  2003/08/08 16:05:37  maclean
// Updates    : stdc++ lib changes
// Updates    :
// Updates    : Revision 1.3  2000/10/19 19:05:04  maclean
// Updates    : in clnt_create, use tcp not netpath
// Updates    :
// Updates    : Revision 1.2  1998/01/29 18:00:31  maclean
// Updates    : Added RCS header
// Updates    :
//
//

/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "nc_server_rpc.h"

#include <iostream>
#include <stdlib.h>

int main(int argc, char *argv[])
{
  char *host;
  CLIENT *clnt;
  int  *res;

  if (argc < 2) {
	  printf("usage:  %s server_host\n", argv[0]);
	  exit(1);
  }
  host = argv[1];

  clnt = clnt_create(host, NETCDFSERVERPROG, NETCDFSERVERVERS, "tcp");
  if (clnt == (CLIENT *) NULL) {
	  clnt_pcreateerror(host);
	  exit(1);
  }

  res = closefiles_1((void *)0, clnt);
  if (res == (int *) NULL) {
	  clnt_perror(clnt, "call failed");
  }
  clnt_destroy(clnt);
}
