//              Copyright (C) by UCAR
//
// File       : $RCSfile: nc_shutdown.cxx,v $
// Revision   : $Revision$
// Directory  : $Source: /code/cvs/pam/isff/src/nc_server/nc_shutdown.cxx,v $
// System     : PAM
// Date       : $Date$
//
// Description:
//
// Updates    : $Log: nc_shutdown.cxx,v $
// Updates    : Revision 1.3  2003/08/08 16:05:38  maclean
// Updates    : stdc++ lib changes
// Updates    :
// Updates    : Revision 1.2  2000/10/19 19:06:20  maclean
// Updates    : in clnt_create, use tcp not netpath
// Updates    :
// Updates    : Revision 1.1  1998/01/29 18:22:15  maclean
// Updates    : initial checkin
// Updates    :
//
//

/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "nc_server_rpc.h"

#include <iostream>
#include <stdlib.h>

int main(int argc, char *argv[])
{
  char *host;
  CLIENT *clnt;

  if (argc < 2) {
	  printf("usage:  %s server_host\n", argv[0]);
	  exit(1);
  }
  host = argv[1];

  clnt = clnt_create(host, NETCDFSERVERPROG, NETCDFSERVERVERS, "tcp");
  if (clnt == (CLIENT *) NULL) {
	  clnt_pcreateerror(host);
	  exit(1);
  }

  shutdown_1((void *)0, clnt);
  clnt_destroy(clnt);
}
