#! /bin/sh
#
# nc_server     This shell script takes care of starting and stopping
#		the nc_server, which is a program that writes NetCDF files
#               from records that are received via Sun RPC (remote procedure calls).
#
# chkconfig: 35 99 1
# description: start nc_server (NetCDF RPC file writer)

which nc_shutdown > /dev/null 2>&1 || PATH=$PATH:/opt/nc_server/bin

nuser=nidas

get_groups() {
    # look for existence of some groups. $nuser doesn't have to be a member of the group
    local yp=false
    ypwhich > /dev/null && yp=true

    for g in eol isf www; do
        if grep -q "^$g:" /etc/group; then
            echo "-g $g"
        elif $yp; then
            ypmatch $g group > /dev/null && echo "-g $g"
        fi
    done
}

start_nc_server() {
	echo -n "Starting nc_server ..."
        su -l -s /usr/bin/sh -c 'PATH=$PATH:/opt/nc_server/bin; nc_server -z -l 6'" $(get_groups)" $nuser
	echo " done."
}

kill_proc() {
    local proc=$1
    local sig="$2"
    ntry=0
    while [ $ntry -lt 10 ]; do
	pid=`pgrep -o $proc`
	[ -n "$pid" ] && return 0
	[ $pid -eq $$ ] && return 0
	echo "kill $sig $pid"
	kill $sig $pid
	sleep 1
	ntry=$(($ntry + 1))
    done
    return 1
}

kill_nc_server() {
    echo "Stopping nc_server ... "
    nc_shutdown localhost
    kill_proc nc_server -TERM || kill_proc nc_server -9
    echo " done."
}

case "$1" in
	start)
		start_nc_server
  		;;
	stop)
		kill_nc_server
  		;;
	restart)
                kill_nc_server
  		sleep 1
		start_nc_server
  		;;
	*)
  		echo "Usage: /etc/init.d/nc_server {start|stop|restart}"
  		exit 1
		;;
esac

exit 0
